# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#gems:
#  - jekyll-sitemap
#  - octopress-minify-html

# Site info
title: Eelviny
name: &name 'Elvin Luff'
author: *name
email: 'elvinluff@gmail.com'
description: >
  My name's Elvin Luff, but I go by the username Eelviny. I am many things: systems administrator, web developer, world traveller, charity worker, student and a complete perfectionist. Welcome to my world.
url: 'https://eelviny.me'
tracking_code: UA-38351552-4
main_color: '#38b0de'
foundation_version: '6.2.0'

# File location
source: ./source
destination: ./static

# Site generation
permalink: /blog/:year/:title/
sass:
  sass_dir: assets/styles
  style: compressed
  
compress_html:
  clippings: all
  comments: all
  endings: all
#  ignore:
#    envs: [development]
