# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
  - jekyll-sitemap
  - octopress-minify-html

# Site settings
title: Eelviny
name: "Elvin Luff"
email: "[not set]"
description: >
  My name's Elvin Luff, but I go by the username Eelviny. I am many things: Web developer, student, outdoor persuits leader, charity worker, systems administrator, and a complete perfectionist. Welcome to my world.
url: "https://eelviny.me"
twitter_username: elvinluff
github_username:  Eelviny
tracking_code: UA-38351552-4
main_colour: '#38b0de'

sass:
    sass_dir: assets/styles
    style: compressed

# File location

source: ./source
destination: ./static

permalink: /blog/:year/:title/
