# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

plugins:
  - jekyll-sitemap

# Site info
title: Eelviny
author: 
  name: 'Elvin Luff'
  email: 'elvinluff@gmail.com'
  twitter: 'elvinluff'
  description: >
    My name's Elvin Luff, but I go by the username Eelviny. I'm an Englishman lost in the Netherlands, with a passion for all things travel and technology. Welcome to my space.
url: 'https://eelviny.me'
twitter:
  username: 'elvinluff'
main_color: '#38b0de'
logo: '/assets/images/icon512.png'
excerpt_separator: <!--more-->

# Site generation
permalink: /blog/:year/:title/
section: 'Blog'
sass:
  sass_dir: assets/styles
  style: compressed
  
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [development]
    
collections:
  projects:
